[{
	"name": "crossdomain_youku",
	"find": "https?:\/\/static\.youku\.com\/(?!(custom)).*?q?(player|loaders?|\w{13})(_[^.]+)?\.swf",
	"monitor": "https?:\/\/v\.youku\.com\/crossdomain\.xml",
	"extra": "crossdomain"
}, {
	"name": "crossdomain_tudou",
	"find": ".*PortalPlayer[^\.]*\.swf",
	"exfind": "https?:\/\/v\.youku\.com\/crossdomain\.xml",
	"monitor": "https?:\/\/www\.tudou\.com\/crossdomain\.xml",
	"extra": "crossdomain"
}, {
	"name": "crossdomain_sohu",
	"find": "https?:\/\/(tv\.sohu\.com\/upload\/swf\/(?!(ap|56|qianfan)).*\d+|(\d+\.){3}\d+(:\d+)?\/webplayer)\/(Main|PlayerShell)[^\.]*\.swf",
	"monitor": "https?:\/\/(photocdn|live\.tv)\.sohu\.com\/crossdomain\.xml",
	"extra": "crossdomain"
}, {
	"name": "crossdomain_iqiyi|pps-c1",
	"find": "https?:\/\/www\.iqiyi\.com\/(player\/(\d+\/Player|[a-z0-9]*|cupid\/.*\/(pps[\w]+|clear))|common\/flashplayer\/\d+\/((PPS)?Main|Coop|share|Enjoy)?(Player[^\.]*|\d+f98c2359))\.swf",
	"monitor": "\w{32}\.\w{3}.*qyid=\w{32}.*ran=\d+",
	"extra": "crossdomain"
}, {
	"name": "crossdomain_iqiyi|pps-c2",
	"find": "https?:\/\/www\.iqiyi\.com\/player\/cupid\/common\/icon\.swf",
	"monitor": "notavailable",
	"extra": "crossdomain"
}, {
	"name": "crossdomain_iqiyi|pps-main",
	"find": "https?:\/\/.*(iqiyi|pps)\.com\/.*\.htm",
	"exfind": "\w{32}\.\w{3}.*qyid=\w{32}.*ran=\d+",
	"monitor": "policy\.video\.iqiyi\.com\/crossdomain\.xml",
	"extra": "crossdomain"
}, {
	"name": "crossdomain_letv",
	"find": "https?:\/\/.*letv[\w]*\.com\/.*\/((?!(Live|seed|Disk))(S[\w]{2,3})?(?!Live)[\w]{4}|swf)Player*\.swf",
	"monitor": "https?:\/\/player\.letvcdn\.com\/crossdomain\.xml",
	"extra": "crossdomain"
}, {
	"name": "crossdomain_douyu",
	"find": "https?:\/\/staticlive\.douyutv\.com\/common\/simplayer\/WebRoomNormal\.swf",
	"monitor": "https?:\/\/www\.douyu\.com\/crossdomain\.xml",
	"extra": "crossdomain"
}, {
	"name": "yk.pp.navi.youku.com:80",
	"find": "",
	"monitor": "",
	"extra": "proxy"
}
]
